=== davidgpgr94/uva-inf-tds-practica1/src/uva/tds/pr1/equipo09/libreta.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!ELEMENT libreta (persona|grupo)*>	
 <!ELEMENT persona (apellidos?,nombre,email+,telef*)>
 <!ELEMENT apellidos (#PCDATA)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT email (#PCDATA)>
 <!ELEMENT telef (#PCDATA)>
 <!ATTLIST telef tipo (MovilPersonal|MovilTrabajo|FijoCasa|FijoTrabajo) "MovilPersonal">
 <!ATTLIST persona alias ID #REQUIRED>
 <!ELEMENT grupo (miembro+)>
 <!ELEMENT miembro EMPTY> 
 <!ATTLIST grupo gNombre ID #REQUIRED>
 <!ATTLIST miembro alias IDREF #REQUIRED>

=== davidgpgr94/uva-inf-tds-practica1/src/uva/tds/pr1/equipo09/libretaMod.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreta SYSTEM "src/uva/tds/pr1/equipo09/libreta.dtd">
<libreta>
 <persona alias="PacoPorras">
   <apellidos>Martin</apellidos>
   <nombre>Paco</nombre>
   <email>email@Paco</email>
   <email>email@Paco2</email>
   <telef tipo="MovilTrabajo">978232521</telef>
 </persona>
 <persona alias="Manolin">
   <apellidos></apellidos>
   <nombre>Manol</nombre>
   <email>email@Manolo</email>
   <telef tipo="FijoCasa">983458691</telef>
   <telef tipo="MovilPersonal">676154876</telef>
 </persona>
 <grupo gNombre="Enemigos">
   <miembro alias="Manolin"/>
 </grupo>
 <persona alias="Danielin">
   <apellidos>Parda</apellidos>
   <nombre>Dani</nombre>
   <email>email@Dani</email>
   <telef tipo="MovilPersonal">965232323</telef>
 </persona>
</libreta>

=== davidgpgr94/uva-inf-tds-practica1/src/uva/tds/pr1/equipo09/libreta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreta SYSTEM "src/uva/tds/pr1/equipo09/libreta.dtd" >
<libreta>
 <persona alias="Danielin">
   <apellidos>Parda</apellidos>
   <nombre>Dani</nombre>
   <email>email@Dani</email>
   <telef tipo="MovilPersonal">965232323</telef>
 </persona>
 <persona alias="PacoPorras">
   <apellidos>Martin</apellidos>
   <nombre>Paco</nombre>
   <email>email@Paco</email>
   <email>email@Paco2</email>
   <telef tipo="MovilTrabajo">978232521</telef>
 </persona>
 <grupo gNombre="Amigos">
     <miembro alias="Danielin"/>
 </grupo>
  <persona alias="Manolin">
   <nombre>Manol</nombre>
   <email>email@Manolo</email>
   <telef>676154876</telef>
   <telef tipo="FijoCasa">983458691</telef>
 </persona>
</libreta>
